name: Tests

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly
            - name: Install Dependencies
              run: yarn
            - name: Update Modules
              run: yarn sync
            - name: Run Tests
              env:
                  ETH_RPC_URL: https://eth-mainnet.alchemyapi.io/jsonrpc/3rP4_tYLdZbRPA1EyuE1CzJ8nuvQqU7z
              run: yarn test
